doctrine_mongodb:
    # Génération automatique en dev, désactivée en prod
    auto_generate_proxy_classes: true
    auto_generate_hydrator_classes: true
    hydrator_dir: '%kernel.cache_dir%/doctrine/odm/mongodb/Hydrator'
    proxy_dir: '%kernel.cache_dir%/doctrine/odm/mongodb/Proxies'
    
    connections:
        default:
            server: '%env(resolve:MONGODB_URL)%'
            options: {}

    default_database: '%env(resolve:MONGODB_DB)%'

    document_managers:
        default:
            auto_mapping: true
            mappings:
                App:
                    dir: '%kernel.project_dir%/src/Document'
                    prefix: 'App\Document'

# Configuration spécifique pour la production
when@prod:
    doctrine_mongodb:
        auto_generate_proxy_classes: false
        auto_generate_hydrator_classes: false
        hydrator_dir: '%kernel.cache_dir%/doctrine/odm/mongodb/Hydrator'
        proxy_dir: '%kernel.cache_dir%/doctrine/odm/mongodb/Proxies'
        document_managers:
            default:
                metadata_cache_driver:
                    type: service
                    id: doctrine_mongodb.system_cache_pool

    framework:
        cache:
            pools:
                doctrine_mongodb.system_cache_pool:
                    adapter: cache.system