# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    trusted_proxies: ['127.0.0.1', '172.16.0.0/12'] # IP de Caddy ou de ton réseau docker
    trusted_headers: ['x-forwarded-for', 'x-forwarded-proto', 'x-forwarded-port', 'x-forwarded-host']

    session:
        handler_id: null
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'

    router:
        default_uri: 'https://localhost'
when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
