name: CI Symfony

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  symfony-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: lsnacksdb_test
          MYSQL_USER: symfony
          MYSQL_PASSWORD: symfony
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        ports:
          - 3306:3306

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          coverage: none
          extensions: mbstring, intl, pdo_mysql

      # 3. Copy test env
      - name: Copy .env.test to .env
        working-directory: ./app
        run: cp .env.test .env

      # 4. Install Composer dependencies
      - name: Install Composer dependencies
        working-directory: ./app
        run: composer install --prefer-dist --no-progress --no-interaction

      # 5. Drop & create test database
      - name: Drop & create test database
        working-directory: ./app
        run: |
          php bin/console doctrine:database:drop --force --env=test || true
          php bin/console doctrine:database:create --env=test

      # 6. Create schema
      - name: Create database schema
        working-directory: ./app
        run: php bin/console doctrine:schema:create --env=test

      # 7. Run PHPUnit tests
      - name: Run PHPUnit
        working-directory: ./app
        run: APP_ENV=test php bin/phpunit --testdox