name: CI Symfony

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  symfony-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          coverage: none
          extensions: mbstring, pdo_sqlite, intl

      - name: Install Composer dependencies (no scripts)
        working-directory: app
        run: composer install --prefer-dist --no-progress --no-interaction --no-scripts

      - name: Prepare test database
        working-directory: app
        run: |
          cp .env.test .env
          mkdir -p var
          php bin/console doctrine:schema:update --force --env=test

      - name: Run PHPUnit tests
        working-directory: app
        run: APP_ENV=test php bin/phpunit --testdox