name: CI Symfony

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  symfony-tests:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer le dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Copier le fichier .env.test avant l'installation de Composer
      - name: Copy test env
        working-directory: ./app
        run: cp .env.test .env

      # 3. Installer PHP et extensions nécessaires
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          coverage: none
          extensions: mbstring, intl, pdo_sqlite, pdo_mysql

      # 4. Installer les dépendances Composer
      - name: Install Composer dependencies
        working-directory: ./app
        run: composer install --prefer-dist --no-progress --no-interaction

      # 5. Supprimer l’ancienne base SQLite pour repartir à zéro
      - name: Reset SQLite DB
        working-directory: ./app
        run: |
          rm -f var/data.db
          mkdir -p var

      # 6. Créer le schéma de base de données
      - name: Create database schema
        working-directory: ./app
        run: php bin/console doctrine:schema:create --env=test

      # 7. Lancer les tests PHPUnit
      - name: Run PHPUnit tests
        working-directory: ./app
        run: APP_ENV=test php bin/phpunit --testdox