name: CI Symfony

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  symfony-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: lsancksdb_test
          MYSQL_USER: symfony
          MYSQL_PASSWORD: symfony
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Copier le fichier .env.test pour CI
      - name: Copy test env
        run: cp app/.env.test app/.env

      # 3. Installer PHP et extensions nécessaires
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: mbstring, intl, pdo_mysql

      # 4. Installer Composer et dépendances
      - name: Install Composer dependencies
        working-directory: ./app
        run: composer install --prefer-dist --no-progress --no-interaction

      # 5. Réinitialiser complètement la base de test
      - name: Reset test database
        working-directory: ./app
        run: |
          php bin/console doctrine:database:drop --force --env=test || true
          php bin/console doctrine:database:create --env=test
          php bin/console doctrine:schema:create --env=test

      # 6. Lancer les tests PHPUnit
      - name: Run PHPUnit tests
        working-directory: ./app
        run: APP_ENV=test php bin/phpunit --testdox