name: CI Symfony Minimal

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]

jobs:
  symfony-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: lsnacksdb_test
          MYSQL_USER: symfony
          MYSQL_PASSWORD: symfony
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=5s
          --health-timeout=3s
          --health-retries=10
      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd="echo 'Mongo is ready'"
          --health-interval=5s
          --health-timeout=3s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, pdo_mysql, mongodb
          coverage: none

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-interaction --working-dir=app

      - name: Copy .env.dist to .env
        run: cp app/.env.dist app/.env

      - name: Wait for MySQL
        run: |
          until mysqladmin ping -h127.0.0.1 -uroot -proot --silent; do
            echo "Waiting for MySQL..."
            sleep 2
          done

      - name: Setup Test Database
        run: |
          php app/bin/console doctrine:database:drop --force --env=test || true
          php app/bin/console doctrine:database:create --env=test
          php app/bin/console doctrine:schema:update --force --env=test
        env:
          DATABASE_URL: "mysql://symfony:symfony@127.0.0.1:3306/lsnacksdb_test"

      - name: Run PHPUnit Minimal Test
        run: cd app && php vendor/bin/phpunit --configuration phpunit.dist.xml --testsuite="Project Test Suite"
        env:
          DATABASE_URL: "mysql://symfony:symfony@127.0.0.1:3306/lsnacksdb_test"
          MONGODB_URL: "mongodb://127.0.0.1:27017"
          MONGODB_DB: "lsnacksdb_test"